### ISSUE TITLE
Cannot Provide Input on Console in Result Tab

### ISSUE THREAD

**Issue by kiddo4** [dartMind-IO/codepad#1]
**Description:**
When executing code on the codelab.dartmind.io platform, the result tab does not allow users to provide input through the console. This functionality is essential for testing interactive applications that require user input.

**Steps to Reproduce:**
1. Navigate to codelab.dartmind.io.
2. Execute a code snippet that requires user input (e.g., using `stdin.readLineSync()` in Dart).
3. Attempt to provide input in the result tab console.

**Expected Behavior:**
The console in the result tab should allow users to provide input when the executed code requests it.

**Actual Behavior:**
The console in the result tab does not accept any input from the user, making it impossible to test code that relies on user input.

**Comment by Yczar** [comment]
Thanks, can you provide the code snippet you used for testing? @kiddo4

**Comment by Yczar** [comment]
@danielAsaboro you can create a github issue on the project for this

**Comment by kiddo4** [comment]
Here is the code:
import 'dart:io';

class Account {
  final int accountNumber;
  final String holderName;
  double _balance = 0.0;

  Account(this.accountNumber, this.holderName);

  double get balance => _balance;

  void deposit(double amount) {
    _balance += amount;
  }

  bool withdraw(double amount) {
    if (amount <= _balance) {
      _balance -= amount;
      return true;
    }
    return false;
  }
}

class Bank {
  int _nextAccountNumber = 1000;
  final Map<int, Account> _accounts = {};

  void createAccount(String holderName) {
    int accountNumber = _nextAccountNumber++;
    Account newAccount = Account(accountNumber, holderName);
    _accounts[accountNumber] = newAccount;
    print('Account created: $accountNumber, Holder: $holderName');
  }

  void deposit(int accountNumber, double amount) {
    Account? account = _accounts[accountNumber];
    if (account != null) {
      account.deposit(amount);
      print('Deposited \$${amount.toStringAsFixed(2)} to account $accountNumber. New balance: \$${account.balance.toStringAsFixed(2)}');
    } else {
      print('Account not found.');
    }
  }

  void withdraw(int accountNumber, double amount) {
    Account? account = _accounts[accountNumber];
    if (account != null) {
      if (account.withdraw(amount)) {
        print('Withdrew \$${amount.toStringAsFixed(2)} from account $accountNumber. New balance: \$${account.balance.toStringAsFixed(2)}');
      } else {
        print('Insufficient funds.');
      }
    } else {
      print('Account not found.');
    }
  }

  void checkBalance(int accountNumber) {
    Account? account = _accounts[accountNumber];
    if (account != null) {
      print('Account $accountNumber balance: \$${account.balance.toStringAsFixed(2)}');
    } else {
      print('Account not found.');
    }
  }
}

void main() {
  Bank bank = Bank();

  while (true) {
    print('\nWelcome to the Bank');
    print('1. Create Account');
    print('2. Deposit');
    print('3. Withdraw');
    print('4. Check Balance');
    print('5. Exit');
    stdout.write('Please select an option: ');
    String? choice = stdin.readLineSync();

    switch (choice) {
      case '1':
        stdout.write('Enter account holder name: ');
        String? name = stdin.readLineSync();
        if (name != null && name.isNotEmpty) {
          bank.createAccount(name);
          print('Account created successfully.');
        } else {
          print('Invalid name.');
        }
        break;
      case '2':
        stdout.write('Enter account number: ');
        int? accountNumber = int.tryParse(stdin.readLineSync() ?? '');
        stdout.write('Enter amount to deposit: ');
        double? amount = double.tryParse(stdin.readLineSync() ?? '');
        if (accountNumber != null && amount != null) {
          bank.deposit(accountNumber, amount);
        } else {
          print('Invalid input.');
        }
        break;
      case '3':
        stdout.write('Enter account number: ');
        int? accountNumber = int.tryParse(stdin.readLineSync() ?? '');
        stdout.write('Enter amount to withdraw: ');
        double? amount = double.tryParse(stdin.readLineSync() ?? '');
        if (accountNumber != null && amount != null) {
          bank.withdraw(accountNumber, amount);
        } else {
          print('Invalid input.');
        }
        break;
      case '4':
        stdout.write('Enter account number: ');
        int? accountNumber = int.tryParse(stdin.readLineSync() ?? '');
        if (accountNumber != null) {
          bank.checkBalance(accountNumber);
        } else {
          print('Invalid account number.');
        }
        break;
      case '5':
        print('Thank you for using the Bank. Goodbye!');
        return;
      default:
        print('Invalid option. Please try again.');
    }
  }
}

**Comment by danielAsaboro** [comment]
thank you, @kiddo4

**Comment by Yczar** [comment]
This is fixed, can you verify @kiddo4 @danielAsaboro

**Comment by kiddo4** [comment]
Yh I've seen the fix it's an input 5ab
